# Generated by Django 4.2.4 on 2023-09-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partnerid', models.IntegerField(primary_key=True, serialize=False)),
                ('partnername', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partner',
            },
        ),
    ]
